# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


mode, cell_size, alive, speed = '', '', '', '' # Defining global variables


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        self.mode_label.setGeometry(QtCore.QRect(10, 5, 56, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.mode_label.setFont(font)
        self.mode_label.setObjectName("mode_label")
        self.game_mode = QtWidgets.QComboBox(self.centralwidget)
        self.game_mode.setGeometry(QtCore.QRect(70, 10, 95, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.game_mode.setFont(font)
        self.game_mode.setObjectName("game_mode")
        self.game_mode.addItem("")
        self.game_mode.addItem("")
        self.speed_label = QtWidgets.QLabel(self.centralwidget)
        self.speed_label.setGeometry(QtCore.QRect(440, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.speed_label.setFont(font)
        self.speed_label.setObjectName("speed_label")
        self.speed_control = QtWidgets.QSlider(self.centralwidget)
        self.speed_control.setGeometry(QtCore.QRect(500, 10, 121, 22))
        self.speed_control.setProperty("value", 20)
        self.speed_control.setOrientation(QtCore.Qt.Horizontal)
        self.speed_control.setObjectName("speed_control")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(720, 9, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 40, 800, 560))
        self.graphicsView.setObjectName("graphicsView")
        self.cell_size_label = QtWidgets.QLabel(self.centralwidget)
        self.cell_size_label.setGeometry(QtCore.QRect(180, 10, 66, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.cell_size_label.setFont(font)
        self.cell_size_label.setObjectName("cell_size_label")
        self.cell_size_control = QtWidgets.QSpinBox(self.centralwidget)
        self.cell_size_control.setGeometry(QtCore.QRect(250, 10, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.cell_size_control.setFont(font)
        self.cell_size_control.setObjectName("cell_size_control")
        self.alive_label = QtWidgets.QLabel(self.centralwidget)
        self.alive_label.setGeometry(QtCore.QRect(310, 10, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.alive_label.setFont(font)
        self.alive_label.setObjectName("alive_label")
        self.alive_control = QtWidgets.QSpinBox(self.centralwidget)
        self.alive_control.setGeometry(QtCore.QRect(375, 10, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.alive_control.setFont(font)
        self.alive_control.setObjectName("alive_control")
        MainWindow.setCentralWidget(self.centralwidget)

        self.start_button.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game Of life by Lamkor"))
        self.mode_label.setText(_translate("MainWindow", "Mode:"))
        self.game_mode.setItemText(0, _translate("MainWindow", "With walls"))
        self.game_mode.setItemText(1, _translate("MainWindow", "No walls"))
        self.speed_label.setText(_translate("MainWindow", "Speed:"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.cell_size_label.setText(_translate("MainWindow", "Cell Size:"))
        self.alive_label.setText(_translate("MainWindow", "Alive %: "))

    def pressed(self):
        n = self.start_button.text()
        if n == 'Start':
            global mode, cell_size, alive, speed
            # runtime started
            print("Program started")
            self.start_button.setText('Stop')
            mode = self.game_mode.currentText()
            cell_size = int(self.cell_size_control.text())
            alive = int(self.alive_control.text())
            speed = int(self.speed_control.value())
            print(mode, cell_size, alive, speed)

        else:
            # runtime stopped
            print("Program stopped")
            self.start_button.setText('Start')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
